config/routes.rb
Kakao::Application.routes.draw do
  resources :groups

  resources :posts, except: [:edit, :update]

  devise_for :users
  resources :users, except: [:destroy, :new, :create]

  resources :search, only: :index

  root to: 'users#index'

end

app/models/addressing.rb
class Addressing < ActiveRecord::Base
  belongs_to :post
  belongs_to :recipient, polymorphic: true
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :parent_group, class_name: 'Group'
  has_many :sub_groups, class_name: 'Group', dependent: :destroy, foreign_key: 'parent_group_id'

  validates_presence_of :name
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :taggings
  has_many :tags, through: :taggings

  has_many :addressings, dependent: :destroy
  has_many :user_recipients, through: :addressings, source: :recipient, source_type: 'User'

  validates_presence_of :text, :user

  def recipients
    # join by type
    user_recipients
  end

  def recipients= recipients
    # split by type
    self.user_recipients = recipients
  end

  def recipient_ids
    recipients.map do |recipient|
      {type: recipient.class.to_s, id: recipient.id, name: recipient.name}
    end
  end

  def recipient_ids= list
    type_lists = {}
    list.each do |identifier|
      type_lists[identifier['type']] ||= []
      type_lists[identifier['type']] << identifier['id']
    end

    type_lists.each do |type, ids|
      send "#{type.downcase}_recipient_ids=", ids
    end
  end

  def serialized_recipient_ids
    recipient_ids.to_json
  end

  def serialized_recipient_ids= params
    self.recipient_ids = JSON.parse params
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def self.reduce tag_name
    tag_name.gsub(/[^[:alnum:]]/, '')
  end
end

app/models/tag_extractor.rb
class TagExtractor
  def initialize post
    @post = post
  end

  def save
    if @post.save
      @post.tags = TagExtractor.extract_tags(@post.text).map do |tag_name|
        Tag.where(name: Tag.reduce(tag_name)).first_or_create!
      end
    end
  end

  def self.extract_tags text
    text.split.reject { |it| it.size <= 1 || !it.start_with?('#') }.map { |it| it[1..-1] }
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :posts

  has_many :addressings, as: :recipient, dependent: :destroy
  has_many :received_posts, through: :addressings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  delegate :tm, to: :view_context

  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_filter :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params.permit(:parent_group_id))

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    if params[:tag]
      @posts = Tag.find(params[:tag]).posts
    else
      @posts = Post.all
    end
    @posts.includes(:tags)
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    extractor = TagExtractor.new @post

    if extractor.save
      redirect_to @post, notice: tm('flash.success.create', Post)
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: tm('flash.success.update', Post)
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:text, :tag_list, :serialized_recipient_ids)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @results = User.where('name ilike ?', "%#{params[:query]}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]

  # TODO remove index and introduce admin interface
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # PATCH/PUT /users/1
  def update
    unless current_user.id.to_s == params[:id]
      redirect_to edit_user_path(current_user), flash: { error: t('user.flash.illegal_update') }
      return
    end

    if current_user.update(user_params)
      redirect_to current_user, notice: tm('flash.success.create', User)
    else
      render action: 'edit'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def translate_with_model(key, model, count = 1)
    translate key, model: model.model_name.human(count: count)
  end
  alias :tm :translate_with_model
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :parent_group %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.parent_group %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<% if @group.parent_group %>
  <p>
    <strong>Parent group:</strong>
    <%= link_to @group.parent_group, @group.parent_group.name %>
  </p>
<% end %>


<p>
  <strong>Sub Groups</strong>
  <ul>
    <% for child in @group.sub_groups %>
      <li><%= link_to child, child.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/_messages.html.erb
<% { error: 'error', notice: 'success'}.each do |k, v| %>
    <% if flash[k] %>
        <div class="alert alert-<%= v %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <div id="flash_<%= k %>">
            <%= flash[k] %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'Kakao', root_path, :class => 'navbar-brand' %>
<ul class="nav navbar-nav pull-right">
  <% if user_signed_in? %>
      <li>
        <%= link_to current_user.name, current_user %>
      </li>
      <li>
        <%= link_to(t('devise.basic.edit'), edit_user_registration_path) %>
      </li>
      <li>
        <%= link_to(t('devise.basic.sign_out'), destroy_user_session_path, :method => 'delete') %>
      </li>
<% else %>
      <li>
      <%= link_to(t('devise.basic.sign_in'), new_user_session_path) %>
      </li>
      <li>
      <%= link_to(t('devise.basic.sign_up'), new_user_registration_path) %>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Kakao' %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <%= render 'layouts/navigation' %>
</nav>

<div id="main" role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
      <footer></footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <%= f.hidden_field :serialized_recipient_ids %>
  <%= f.input :text %>

  <%= f.button :submit %>
<% end %>

app/views/posts/_post.html.erb
<p>
  <%= post.user.name %>
</p>
<p>
  <%= post.text %>
</p>

<p>
  <strong>Tags:</strong>
  <% post.tags.each do |tag| %>
      <%= link_to "##{tag.name}", posts_path(tag: tag.id) %>
  <% end %>
</p>

<%= link_to t('destroy'), post, method: :delete, data: { confirm: t('confirm') } %>

app/views/posts/edit.html.erb
<h1><%= tm 'editing', Post %></h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1><%= tm 'listing', Post, :many %></h1>

<%= render @posts %>

<br />

<%= link_to tm('new', Post), new_post_path %>

app/views/posts/new.html.erb
<h1><%= tm('new', Post) %></h1>

<%= render 'form' %>

<%= link_to t('back'), posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @post %>

<%= link_to t('back'), posts_path %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
    <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<h1><%= tm 'editing', User %></h1>

<%= render 'form' %>

<%= link_to t('show'), @user %> |
<%= link_to t('back'), users_path %>

app/views/users/index.html.erb
<h1><%= tm 'listing', User, :many %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to t('show'), user %></td>
      <td><%= link_to t('edit'), edit_user_path(user) %></td>
      <td><%= link_to t('destroy'), user, method: :delete, data: { confirm: t('confirm') } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<%= link_to t('edit'), edit_user_path(@user) %> |
<%= link_to t('back'), users_path %>